/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner{}

// UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner struct for UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner
type UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner struct {
	Type string `json:"type"`
	Id float32 `json:"id"`
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner

// NewUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner instantiates a new UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner(type_ string, id float32, name string) *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner {
	this := UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner{}
	this.Type = type_
	this.Id = id
	this.Name = name
	return &this
}

// NewUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInnerWithDefaults instantiates a new UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInnerWithDefaults() *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner {
	this := UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner{}
	return &this
}

// GetType returns the Type field value
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) SetId(v float32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) SetName(v string) {
	o.Name = v
}

func (o UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner := _UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner{}

	err = json.Unmarshal(data, &varUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner)

	if err != nil {
		return err
	}

	*o = UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner(varUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner struct {
	value *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner
	isSet bool
}

func (v NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) Get() *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner {
	return v.value
}

func (v *NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) Set(val *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner(val *UserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) *NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner {
	return &NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner{value: val, isSet: true}
}

func (v NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTasksTaskIdSubmitPatch200ResponseDataUserTaskAssigneesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


