/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// UserTasksGetAssignedToUsersParameter Filter tasks by assignment. Provide one or more user ids. If not provided, returns all accessible tasks.
type UserTasksGetAssignedToUsersParameter struct {
	[]string *[]string
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *UserTasksGetAssignedToUsersParameter) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into []string
	err = json.Unmarshal(data, &dst.[]string);
	if err == nil {
		json[]string, _ := json.Marshal(dst.[]string)
		if string(json[]string) == "{}" { // empty struct
			dst.[]string = nil
		} else {
			return nil // data stored in dst.[]string, return on the first match
		}
	} else {
		dst.[]string = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(UserTasksGetAssignedToUsersParameter)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *UserTasksGetAssignedToUsersParameter) MarshalJSON() ([]byte, error) {
	if src.[]string != nil {
		return json.Marshal(&src.[]string)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableUserTasksGetAssignedToUsersParameter struct {
	value *UserTasksGetAssignedToUsersParameter
	isSet bool
}

func (v NullableUserTasksGetAssignedToUsersParameter) Get() *UserTasksGetAssignedToUsersParameter {
	return v.value
}

func (v *NullableUserTasksGetAssignedToUsersParameter) Set(val *UserTasksGetAssignedToUsersParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTasksGetAssignedToUsersParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTasksGetAssignedToUsersParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTasksGetAssignedToUsersParameter(val *UserTasksGetAssignedToUsersParameter) *NullableUserTasksGetAssignedToUsersParameter {
	return &NullableUserTasksGetAssignedToUsersParameter{value: val, isSet: true}
}

func (v NullableUserTasksGetAssignedToUsersParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTasksGetAssignedToUsersParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


