/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the SourceControlManifestsManifestNameGet200ResponseDataManifest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceControlManifestsManifestNameGet200ResponseDataManifest{}

// SourceControlManifestsManifestNameGet200ResponseDataManifest The specified release manifest
type SourceControlManifestsManifestNameGet200ResponseDataManifest struct {
	Name string `json:"name"`
	Apps []SourceControlManifestsGet200ResponseDataManifestsInnerAppsInner `json:"apps"`
	AdditionalProperties map[string]interface{}
}

type _SourceControlManifestsManifestNameGet200ResponseDataManifest SourceControlManifestsManifestNameGet200ResponseDataManifest

// NewSourceControlManifestsManifestNameGet200ResponseDataManifest instantiates a new SourceControlManifestsManifestNameGet200ResponseDataManifest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceControlManifestsManifestNameGet200ResponseDataManifest(name string, apps []SourceControlManifestsGet200ResponseDataManifestsInnerAppsInner) *SourceControlManifestsManifestNameGet200ResponseDataManifest {
	this := SourceControlManifestsManifestNameGet200ResponseDataManifest{}
	this.Name = name
	this.Apps = apps
	return &this
}

// NewSourceControlManifestsManifestNameGet200ResponseDataManifestWithDefaults instantiates a new SourceControlManifestsManifestNameGet200ResponseDataManifest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceControlManifestsManifestNameGet200ResponseDataManifestWithDefaults() *SourceControlManifestsManifestNameGet200ResponseDataManifest {
	this := SourceControlManifestsManifestNameGet200ResponseDataManifest{}
	return &this
}

// GetName returns the Name field value
func (o *SourceControlManifestsManifestNameGet200ResponseDataManifest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SourceControlManifestsManifestNameGet200ResponseDataManifest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SourceControlManifestsManifestNameGet200ResponseDataManifest) SetName(v string) {
	o.Name = v
}

// GetApps returns the Apps field value
func (o *SourceControlManifestsManifestNameGet200ResponseDataManifest) GetApps() []SourceControlManifestsGet200ResponseDataManifestsInnerAppsInner {
	if o == nil {
		var ret []SourceControlManifestsGet200ResponseDataManifestsInnerAppsInner
		return ret
	}

	return o.Apps
}

// GetAppsOk returns a tuple with the Apps field value
// and a boolean to check if the value has been set.
func (o *SourceControlManifestsManifestNameGet200ResponseDataManifest) GetAppsOk() ([]SourceControlManifestsGet200ResponseDataManifestsInnerAppsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Apps, true
}

// SetApps sets field value
func (o *SourceControlManifestsManifestNameGet200ResponseDataManifest) SetApps(v []SourceControlManifestsGet200ResponseDataManifestsInnerAppsInner) {
	o.Apps = v
}

func (o SourceControlManifestsManifestNameGet200ResponseDataManifest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceControlManifestsManifestNameGet200ResponseDataManifest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["apps"] = o.Apps

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SourceControlManifestsManifestNameGet200ResponseDataManifest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"apps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceControlManifestsManifestNameGet200ResponseDataManifest := _SourceControlManifestsManifestNameGet200ResponseDataManifest{}

	err = json.Unmarshal(data, &varSourceControlManifestsManifestNameGet200ResponseDataManifest)

	if err != nil {
		return err
	}

	*o = SourceControlManifestsManifestNameGet200ResponseDataManifest(varSourceControlManifestsManifestNameGet200ResponseDataManifest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "apps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSourceControlManifestsManifestNameGet200ResponseDataManifest struct {
	value *SourceControlManifestsManifestNameGet200ResponseDataManifest
	isSet bool
}

func (v NullableSourceControlManifestsManifestNameGet200ResponseDataManifest) Get() *SourceControlManifestsManifestNameGet200ResponseDataManifest {
	return v.value
}

func (v *NullableSourceControlManifestsManifestNameGet200ResponseDataManifest) Set(val *SourceControlManifestsManifestNameGet200ResponseDataManifest) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceControlManifestsManifestNameGet200ResponseDataManifest) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceControlManifestsManifestNameGet200ResponseDataManifest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceControlManifestsManifestNameGet200ResponseDataManifest(val *SourceControlManifestsManifestNameGet200ResponseDataManifest) *NullableSourceControlManifestsManifestNameGet200ResponseDataManifest {
	return &NullableSourceControlManifestsManifestNameGet200ResponseDataManifest{value: val, isSet: true}
}

func (v NullableSourceControlManifestsManifestNameGet200ResponseDataManifest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceControlManifestsManifestNameGet200ResponseDataManifest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


